#ifndef NETWORK_UTILITY_H_
#define NETWORK_UTILITY_H_

#define SERVER_MAILBOX 0
#define CLIENT_MAILBOX 1

#define CREATE_LOCK 1
#define ACQUIRE_LOCK 2
#define RELEASE_LOCK 3
#define DESTROY_LOCK 4

#endif
